apps/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginView, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logoutView, name='logout'),
    path('recuperar_contraseña/', views.recuperar_contraseña, name='recuperar_contraseña'),        
    path('cambiar_password/', views.cambiar_password_primera_vez, name='cambiar_password_primera_vez'),
    path('permisos_insuficientes/', views.permisos_insuficientes, name="permisos_insuficientes"),
    path('baja_membresia/<int:pk>', views.baja_membresia, name='baja_membresia'),
    path('actualizar_membresia/<int:pk>', views.actualizar_membresia, name='actualizar_membresia'),
    path('actualizar_asistencia/', views.actualizar_asistencia, name='actualizar_asistencia'),
    path('crear_asistencia/', views.crear_asistencia, name='crear_asistencia')
]

gymadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from apps.core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('abm/', include('apps.abm.urls')),
    #path('', views.home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/forms.py
from django import forms
from datetime import date,timedelta
from django.conf import settings

class CrearAsistenciaForm (forms.Form):
    dni = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control', 'step': '1'}))

class ActualizarMembresiaForm(forms.Form):
    ESTADO_MEMBRESIA = [
        ('Activa', 'Activa'),
        ('Adeuda', 'Adeuda'),
        ('Baja', 'Baja'),
    ]
    METODO_PAGO = [
        ('Efectivo','Efectivo'),
        ('Tarjeta','Tarjeta'),
        ('Transferencia', 'Transferencia')
    ]
    fecha_inicio = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    fecha_fin = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    estado = forms.ChoiceField(choices=ESTADO_MEMBRESIA, widget=forms.Select(attrs={'class': 'form-control'}))
    importe = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01'}))
    metodo_pago = forms.ChoiceField(choices=METODO_PAGO, widget=forms.Select(attrs={'class': 'form-control'}))
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #rellena la form con la fecha de hoy, 30 dias de hoy, precio en settings y activa por defecto.
        fecha_hoy = date.today()
        self.fields['fecha_inicio'].initial = fecha_hoy
        self.fields['fecha_fin'].initial = fecha_hoy + timedelta(days=30)
        self.fields['importe'].initial = settings.PRECIO_MES_SUSCRIPCION
        self.fields['estado'].initial = 'Activa'

apps/core/views.py
from django.shortcuts import render,redirect
#vista basada en clases
from django.views import View

#vista basada en funciones 
from django.http import HttpResponse
from django.http import JsonResponse

#importar authenticate
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages

#importar modelos
from .forms import CrearAsistenciaForm, ActualizarMembresiaForm
from apps.abm.models import Cliente, UserProfile, Asistencia, Membresia, Cobranza

#importar tiempo para asistencia
from django.utils import timezone
from datetime import timedelta

#importa correo
from apps.core.utils import enviar_correo, recibir_correo
from django.contrib.auth.models import User
import random, string

#importar conf
from django.conf import settings

#exepciones
from django.core.exceptions import ObjectDoesNotExist

def home(request):
    form = CrearAsistenciaForm()

    #formulario de asistencia
    if request.method == 'POST' and 'dni' in request.POST:
        print(request.POST)
        form = CrearAsistenciaForm(request.POST)
        if form.is_valid():
            dni = form.cleaned_data['dni']
            try :
                usuario = UserProfile.objects.get(dni=dni)
            except UserProfile.DoesNotExist:
                usuario = None
                
            else:
                try :
                    c = Cliente.objects.get(usuario=usuario)
                    entrada = timezone.now()
                    salida = entrada + timedelta(hours=2)
                    Asistencia.objects.create(cliente=c,
                                              hora_entrada=entrada,
                                              hora_salida=salida,
                                              capacidad=100)
                    #cambiar capacidad dependiendo
                except Cliente.DoesNotExist:
                    usuario = None

            if not usuario:
                contexto = {
                    'mensaje': 'El usuario no está registrado en la base.',
                    'cantidad': Asistencia.objects.count(),
                    'form' : form,
                }
                return render(request, 'home.html', contexto)
        
    #formulario de contacto
    if request.method == 'POST' and 'nombre' in request.POST:
        nombre = request.POST.get('nombre')
        email = request.POST.get('email')
        mensaje = request.POST.get('mensaje')

        cuerpo = f"Nombre: {nombre}\nEmail: {email}\nMensaje:\n{mensaje}"

        recibir_correo(
            remitente=email,
            asunto="Comunicacion - Nuevo mensaje desde la web",
            contexto=cuerpo,
            plantilla_html=None
        )
        return redirect('home')

    contexto = {
        'form': form,
    }
    return render(request, 'home.html', contexto)


def proteger_login(view_func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('dashboard')
        return view_func(request, *args, **kwargs)
    return wrapper

@proteger_login
def loginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None : 
            login(request, user)
            try:
                profile = UserProfile.objects.get(user=user)
                if profile.first_login:
                    return redirect('cambiar_password_primera_vez')
                return redirect('dashboard')
            
            except UserProfile.DoesNotExist:
                mensaje = 'No existe un perfil de usuario asociado.'
                contexto = {
                    'mensaje': mensaje,
                }
                logout(request)
                return render(request, 'login.html', contexto)
        else :
            mensaje ='Usuario y/o contraseña invalido.'
            contexto = {
             'mensaje' : mensaje,
            }
            return render(request, 'login.html', contexto)
        
    contexto = {}
    
    return render(request, 'login.html', contexto)

@login_required
def cambiar_password_primera_vez(request):
    if request.method == 'POST':
        new_password = request.POST.get('new_password')
        confirm_password = request.POST.get('confirm_password')

        if new_password == confirm_password:
            user = request.user
            user.set_password(new_password)
            user.save()
            
            user.user_usuario.first_login = False
            user.user_usuario.save()

            update_session_auth_hash(request, user)

            messages.success(request, 'Contraseña cambiada correctamente.')
            logout(request)
            return redirect('login')
        else:
            messages.error(request, 'Las contraseñas no coinciden.')

    return render(request, 'first_login.html')

@login_required
def logoutView(request):
    logout(request)
    return redirect('home')

@login_required
def dashboard(request):
    nuevaCobranza = None
    usuario = request.user
    contexto = {
        'user' : usuario,
    }
    if usuario.is_staff:
        miembrosAdeudados = list(Membresia.objects.filter(estado='Adeuda'))
        cobranzas = []
        for miembro in miembrosAdeudados:
            nuevaCobranza = Cobranza(
                membresia=miembro,
                importe=settings.PRECIO_MES_SUSCRIPCION,
                fecha_pago='A Decidir',
                metodo_pago='A decidir'
                )
            setattr(nuevaCobranza, "a_pagar", "true")
            cobranzas.append(nuevaCobranza)
        contexto['cobranzas'] = cobranzas
        return render (request, 'dashboard.html', contexto)
    else:
        try:
            membresia = usuario.user_usuario.cliente_usuario.membresia_cliente
            contexto['membresia'] = membresia
            cobranzas = Cobranza.objects.filter(membresia=membresia)
            contexto['cobranzas'] = list(cobranzas)
            if membresia.estado == 'Adeuda':
                nuevaCobranza = Cobranza(
                    membresia=membresia,
                    importe=settings.PRECIO_MES_SUSCRIPCION,
                    fecha_pago='A Decidir',
                    metodo_pago= 'A Decidir'
                    )
                setattr(nuevaCobranza, "a_pagar", "true")
                if nuevaCobranza:
                    contexto['cobranzas'].append(nuevaCobranza)

        except ObjectDoesNotExist:
            mensaje ='Cliente o Membresia no validas.'
            contexto = {
                'mensaje' : mensaje,
            }

            enviar_correo(
                asunto="Error - Login sin cliente/membresia",
                destinatario=settings.EMAIL_HOST_USER,
                contexto="Un usuario tiene problemas para iniciar sesion por no figurar en las listas de clientes o membresia.\n"
                "\nApellido y Nombre: " + usuario.last_name + " " + usuario.first_name + 
                "\nEmail: " + usuario.email + 
                "\nDNI: " + str(usuario.user_usuario.dni),
                plantilla_html=""
            )
            
            logout(request)
            return render(request, 'login.html', contexto)

    return render(request, 'dashboard.html', contexto)
""""
@login_required
def dashboard(request):
    # 🔹 Si es primer login, obligamos a cambiar la contraseña
    if request.user.userprofile.first_login:
        return redirect('cambiar_password_primera_vez')
        """



#implementacion de correos

def generar_contraseña_temporal(longitud=8):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=longitud))

def recuperar_contraseña(request):
    mensaje = ""
    exito = False
    if request.method == "POST":
        email = request.POST.get("email")
        try: 
            correo = User.objects.get(email=email)
            usuario = UserProfile.objects.get(user=correo)
            nueva_pass = generar_contraseña_temporal()
            correo.set_password(nueva_pass)
            correo.save()
            usuario.first_login = True
            usuario.save()
            contexto = {
                "usuario": correo.username,
                "nueva_pass": nueva_pass,
            }
            enviar_correo(
                asunto="Recuperación de contraseña",
                destinatario=email,
                contexto=str(contexto),
                plantilla_html=""
            )
            exito = True
            mensaje = "Se ha enviado una nueva contraseña a tu correo."
        except User.DoesNotExist:
            mensaje = "No existe un usuario con ese correo."
            exito = False

    return render(request, "recuperar_contraseña.html", {"mensaje": mensaje, "exito": exito})

def permisos_insuficientes(request):
    return render(request, "permisos_insuficientes.html", {"mensaje" : 'mensaje'})

@staff_member_required(login_url='/permisos_insuficientes/')
def actualizar_membresia (request, pk):
    form = ActualizarMembresiaForm()
    membresia = Membresia.objects.get(id=pk)
    contexto = {
        'form' : form,
        'membresia': membresia,
    }
    if request.method == "POST":
        form = ActualizarMembresiaForm(request.POST)
        if form.is_valid():
            membresia.fecha_inicio = form.cleaned_data['fecha_inicio']
            membresia.fecha_fin = form.cleaned_data['fecha_fin']
            membresia.estado = form.cleaned_data['estado']
            membresia.save()

            cobranza = Cobranza.objects.create( membresia=membresia,
                                                importe=form.cleaned_data['importe'],
                                                metodo_pago=form.cleaned_data['metodo_pago']

apps/core/templates/actualizar_membresia.html
{% extends "base.html" %}

{% block extra_css %}
    <style>
        .form-control:focus {
            border-color: #003366 !important; /* azul oscuro */
            box-shadow: 0 0 0 0.2rem rgba(0, 51, 102, 0.25); /* brillito azul */
        }
        .form-control {
            border: 2px solid #000000 !important; /* borde negro */
        }
</style>
{% endblock %}

{% block content %}
<div class="d-flex">    <!--formulario para actualizar Cobranza-->

    <div class="flex-grow-1 p-4">
        <h2 class="mb-4">Actualizar membresia para {{membresia.cliente.usuario.user.first_name}} {{membresia.cliente.usuario.user.last_name}}</h2>
        <a href="{% url 'dashboard' %}">
            <button type="button" class="btn btn-sm btn-secondary mb-1">Volver</button>
        </a>
        <form method="post">
            <div class="mb-3 d-flex justify-content-evenly" style="color: #000000">
                {% csrf_token %}
                <div class="model-form p-3 flex-column col-md-4 bg-white rounded">
                    <h4>Datos de Membresia</h4>
                    <br>
                    <p>
                        <label for="importe">Fecha de inicio:</label>
                        {{ form.fecha_inicio }}
                    </p>
                    <p>
                        <label for="metodo_pago">Fecha vencimiento:</label>
                        {{ form.fecha_fin }}
                    </p>
                    <p>
                        <label for="metodo_pago">Estado:</label>
                        {{ form.estado }}
                    </p>
                </div>
                <div class="model-form p-3 flex-column col-md-4 bg-white rounded">
                    <h4>Datos de Cobranza</h4>
                    <br>
                    <p>
                        <label for="importe">Importe:</label>
                        {{ form.importe }}
                    </p>
                    <p>
                        <label for="metodo_pago">Metodo de pago:</label>
                        {{ form.metodo_pago }}
                </div>
            </div>
            <div class="text-center p-3">
                <button type="submit" class="btn btn-primary">Registrar cobranza</button>
            </div>
        </form>
     </div>
</div>

{% endblock %}

apps/core/templates/base.html
{% load static %} 
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Proyecto Django{% endblock %}</title>
    <link href="{% static '/images/icono.ico' %}" rel="icon">
    

    <!-- Bootstrap 5 CSS -->
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
        crossorigin="anonymous">

    <!-- Bootstrap Icons -->
    <link 
        rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    <!-- DataTables CSS -->
    <link 
        rel="stylesheet" 
        href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css">

    <!-- Select2 CSS -->
    <link 
        href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" 
        rel="stylesheet" />


        <style>
        body{
            background-color: #1E3357;
            color: #F0F0F0;
        }
    </style>

    {% block extra_css %}
    
    {% endblock %}
</head>
<body>
    
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <!-- Logo -->
            <a class="navbar-brand" href="{% url 'home' %}">GimAdmin</a>

            <!-- Botón hamburguesa en móviles -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links del menú -->
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <!-- Ejemplo de link -->
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
                    </li>
                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuario_listar' %}">Usuarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cliente_listar' %}">Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'membresia_listar' %}">Membresías</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'asistencia_listar' %}">Asistencias</a>
                    </li>
                    {% endif %}
                    {% endif %}
                </ul>
                
                <!-- Botón iniciar sesión -->
                <div class="d-flex">
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}" class="btn btn-outline-light">
                        <i class="bi bi-box-arrow-in-left"></i> Cerrar sesión
                    </a>
                    {% elif request.resolver_match.url_name == 'login' %}
                    <!-- Botón home -->
                    <div class="d-flex">
                        <a href="{% url 'home' %}" class="btn btn-outline-light">
                            Volver a home
                        </a>
                    </div>
                    {% else %}
                    <a href="{% url 'login' %}" class="btn btn-outline-light">
                        <i class="bi bi-box-arrow-in-right"></i> Iniciar sesión
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <!-- Contenido principal -->
    <main class=>
        
        {% block content %}
        <!-- Aquí va el contenido de cada plantilla hija -->
        {% endblock %}
        
    </main>

    <!-- jquery js -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

    <!-- -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Datatables js -->
    <script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script>

    {% block script %}

    {% endblock %}

apps/core/templates/crearUsuario.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex">
    <!-- Sidebar -->
    <nav class="bg-blue sidebar p-3" style="width: 220px; min-height: 100vh;">  
        <h5 class="mb-4">Administración</h5>
        <ul class="nav flex-column" style="background-color: #143669">
            <li class="nav-item mb-2 color-white bg-gradient bg-blue-dark">
                <a class="nav-link link-light" href="{% url 'cliente_abm' %}">ABM Cliente</a>
            </li>
            <li class="nav-item mb-2 color-white bg-gradient bg-blue-dark">
                <a class="nav-link link-light" href="{% url 'membresia_abm' %}">ABM Membresía</a>
            </li>
            <li class="nav-item mb-2 color-white bg-gradient bg-blue-dark">
                <a class="nav-link link-light" href="{% url 'asistencia_abm' %}">ABM Asistencia</a>
            </li>
        </ul>
    </nav>

     <div class="flex-grow-1 p-4">
        <h2 class="mb-4">Crear Usuario</h2>     <button type="button" class="btn btn-sm btn-secondary mb-1">Volver</button>
        <form method="post">
            {% csrf_token %}
            {{ userForm }}
            {{ usuarioForm }}
            <button type="submit" class="btn btn-primary">Registrar Usuario</button>
        </form>
     </div>



{%endblock %}

apps/core/templates/first_login.html
{% extends "base.html" %}

{% block title %}Cambiar contraseña{% endblock %}

{% block extra_css %}
<style>
    section {
        min-height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        scroll-behavior: smooth;
    }

    #btn-top {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 1000;
    }
</style>
{% endblock %}

{% block content %}
<div class="col-md-6 mb-4 mx-auto text-center">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}

    <h2>Cambiar contraseña</h2>
    <p>Por seguridad, necesitás establecer una nueva contraseña antes de continuar.</p>

    <form method="post" action="{% url 'cambiar_password_primera_vez' %}" class="text-center">
        {% csrf_token %}
        <br>
        <div class="mb-3">
            <label for="new_password" class="form-label text-start">Nueva contraseña</label>
            <input type="password" id="new_password" name="new_password" class="form-control" required placeholder="Ingresá tu nueva contraseña">
        </div>

        <div class="mb-3">
            <label for="confirm_password" class="form-label text-start">Confirmar contraseña</label>
            <input type="password" id="confirm_password" name="confirm_password" class="form-control" required placeholder="Repetí la contraseña">
        </div>

        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>

<!-- Botón volver arriba -->
<a id="btn-top" href="#banner" class="btn btn-danger btn-lg rounded-circle">
    <i class="bi bi-arrow-up"></i>
</a>
{% endblock %}

apps/core/templates/home.html
{% extends "base.html" %}

{% block title %}GimAdmin{% endblock %}

{% load static %}
{% block extra_css %}
<style>
    /* Secciones de altura completa */
    section {
        /* min-height: 100vh; */
        display: flex;
        justify-content: center;
        align-items: center;
        scroll-behavior: smooth;
        padding: 1em;
    }

    /* Banner */
    #banner {
        background-color: #1e3357; /* temporal, reemplazar con imagen de fondo */
        flex-direction: column;
        text-align: center;
        padding: 50px 20px;
    }

    /* Ocupación */
    #ocupacion {
        /*background-color: #dc3545; /* rojo */
        color: white;
        flex-direction: column;
        text-align: center;
    }
    #ocupacion h1 {
        font-size: 8rem;
        margin: 0;
    }

    /* Contacto */
    #contacto {
        background-color: #f8f9fa;
        flex-direction: column;
        padding: 50px 0;
    }

    /* Botón flotante */
    #btn-top {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 1000;
    }
</style>
{% endblock %}

{% block content %}

<!-- Sección Banner -->
<section id="banner">
    <h1 class="display-4">Bienvenido a GymAdmin</h1>
    <p class="lead mb-4">Tu gimnasio, tu control</p>
    <!-- Placeholder para imágenes del gimnasio -->
    <div class="mb-4">
        <img src="{% static '/images/logo_transparente.png' %}" width="500">
    </div>

    {% if user.is_staff %}
    <!-- Formulario de registro de visita -->
    <div class="alert alert-danger d-flex align-items-center" role="alert" id="div_visible" >
        <!--<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>-->
        <div id="div_error"></div>
    </div>
    <div class="card shadow-sm border-0 rounded-3 w-50 mx-auto p-4 " style="background-color: #355B9C; color: #f8f9fa;">
        <h5 class="mb-3">Registrar visita</h5>
        <div class="input-group">
            <input type="number" name="dni" value="" class="form-control" step="1" id="id_dni">
            <button class="btn btn-primary" id="btn_registro">
            Registrar
            </button>
        </div>
    </div>
    {% endif %}
</section>

<!-- Sección Ocupación -->
 
{% if cantidad > 12 %}
<section id="ocupacion" class="rounded .container-fluid">
    {% else %}
<section id="ocupacion" class="rounded .container-fluid">
    {% endif %}

    <h3>Ocupación:</h3>
    <h1 id="cantidadClientes"></h1>
    <script>
        // Función que hace el fetch y actualiza la interfaz
        function actualizarAsistencia() {
            fetch("actualizar_asistencia")
                .then(response => response.json())
                .then(data => {
                    document.getElementById("cantidadClientes").innerText = data.cantidad;
                    document.getElementById("ocupacion").style.backgroundColor = data.color;
                    
                })
                .catch(err => console.error("Error al actualizar asistencia:", err));
        }

        function crearAsistencia(){
            let dni = document.getElementById("id_dni").value


            fetch("crear_asistencia/?dni=" + dni)
                .then(response => response.json())
                .then(data => {
                    const divError = document.getElementById("div_error");
                    const divVisible = document.getElementById("div_visible");

                    //divVisible.classList.toggle("d-none", data.mensaje && data.mensaje.trim() !== ""); 
                    if (data.mensaje && data.mensaje.trim() !== "") {
                        divVisible.classList.remove("d-none");
                        divError.innerText = data.mensaje;
                    } else {
                        divVisible.classList.add("d-none");
                        divError.innerText = "";
                    }
                    document.getElementById("id_dni").value = "";
                })
                .catch(err => console.error("Error al actualizar asistencia:", err));
        }

        document.addEventListener("DOMContentLoaded", () => {
            const divVisible = document.getElementById("div_visible");
            divVisible.classList.add("d-none");
            actualizarAsistencia();
        }); //cuando carga

        //Cada 2 minutos
        setInterval(actualizarAsistencia, 2000); //1k = 1seg

        //Cuando se presione el btn_registro (carga de asistencia)
        document.getElementById("btn_registro").addEventListener("click", () => {
            crearAsistencia();
            actualizarAsistencia();
        });

        document.getElementById("id_dni").addEventListener("keydown", function(e) {
            if (e.key === "Enter") {
                e.preventDefault();
                document.getElementById("btn_registro").click();
            }
        });

    </script>
</section>


<!-- Sección Contacto -->
<section id="contacto">
    <div class="container text-dark">
         <div class="row">
            <!-- Formulario -->
            <div class="col-md-6 mb-4">
                <h2>Contáctanos</h2>
                <form method="post" action="#">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="nombre" name="nombre" required>
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Correo</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="mb-3">
                        <label for="mensaje" class="form-label">Mensaje</label>
                        <textarea class="form-control" id="mensaje" name="mensaje" rows="4" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>
            </div>
            <!-- Mapa -->
            <div class="col-md-6">
                <h2>Ubicación</h2>
                <div class="ratio ratio-16x9">
                    <iframe 
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2903.7201607380352!2d-65.09611348074361!3d-43.2991817061995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xbe01570fd77559a5%3A0x41e4d247a88a478b!2sCentro%20de%20Actividad%20Fisica%20Oxygeno!5e0!3m2!1ses!2sar!4v1764605773327!5m2!1ses!2sar" 
                        width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
                    </iframe>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Botón volver arriba -->
<a id="btn-top" href="#banner" class="btn btn-danger btn-lg rounded-circle">
    <i class="bi bi-arrow-up"></i>
</a>

{% endblock %}
<!--
{% block extra_js %}
<script>
    // Scroll suave para links del navbar
    document.querySelectorAll('a.nav-link').forEach(anchor => {
        anchor.addEventListener('click', function(e){
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            target.scrollIntoView({ behavior: 'smooth' });
        });
    });
</script>
{% endblock %}-->